#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo '🤔🤔🤔🤔... 🏗️👷 Let see if test cases are passed before pushing. 🤔🤔🤔🤔'
yarn prepush ||
(
    echo '❌👷🔨❌ Better call Bob... Because your tests are failed ❌👷🔨❌
            Nest test failed: View the errors above to see why. 
    '
    false;
)

echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'
yarn build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅